<?xml version="1.0" encoding="UTF-8"?>
<con:wsdlEntry xmlns:con="http://www.bea.com/wli/sb/resources/config">
    <con:wsdl><![CDATA[<wsdl:definitions name="CreditEquifaxMock" targetNamespace="http://www.elliemae.com/service/credit" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ellie="http://www.elliemae.com/service/credit" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    
    <wsdl:documentation> 
    This service provides a common interface to mock Equifax VPS
    </wsdl:documentation>

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://www.elliemae.com/service/credit" schemaLocation="../../../CreditService/Resource/xsd/EMCRequestExtended.xsd"/>
            <xsd:import namespace="http://www.elliemae.com/service/credit" schemaLocation="../../../CreditService/Resource/xsd/EMCResponseExtended.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:portType name="CreditEndPoint">
        <wsdl:documentation>credit operations</wsdl:documentation>
        
        <wsdl:operation name="requestCredit">
            <wsdl:documentation>get the credit score requested from the matching vendor</wsdl:documentation>
            <wsdl:input message="ellie:CreditRequestMsg"/>
            <wsdl:output message="ellie:CreditResponseMsg"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:message name="CreditRequestMsg">
        <wsdl:part name="input" element="ellie:REQUEST_GROUP"/>
    </wsdl:message>
     
    <wsdl:message name="CreditResponseMsg">
        <wsdl:part name="output" element="ellie:RESPONSE_GROUP"/>
    </wsdl:message>

    <wsdl:binding name="CreditBinding" type="ellie:CreditEndPoint">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="requestCredit">
        <soap:operation soapAction="http://www.elliemae.com/service/credit"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

</wsdl:definitions>]]></con:wsdl>
    <con:dependencies>
        <con:schemaRef isInclude="false" schemaLocation="../../../CreditService/Resource/xsd/EMCResponseExtended.xsd" namespace="http://www.elliemae.com/service/credit" ref="EllieMaeNetwork_v1.0/CreditService/Resource/xsd/EMCResponseExtended"/>
        <con:schemaRef isInclude="false" schemaLocation="../../../CreditService/Resource/xsd/EMCRequestExtended.xsd" namespace="http://www.elliemae.com/service/credit" ref="EllieMaeNetwork_v1.0/CreditService/Resource/xsd/EMCRequestExtended"/>
    </con:dependencies>
    <con:targetNamespace>http://www.elliemae.com/service/credit</con:targetNamespace>
</con:wsdlEntry>